# Generated by Django 6.0.5 on 2026-07-21 18:22

import apps.solicitacoes.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='COPPM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
                ('sigla', models.CharField(max_length=20, unique=True)),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'COPPM',
                'verbose_name_plural': 'COPPM',
                'ordering': ['sigla'],
            },
        ),
        migrations.CreateModel(
            name='Modulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120, unique=True)),
                ('descricao', models.TextField(blank=True)),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120, unique=True)),
                ('ibge', models.CharField(blank=True, max_length=10, null=True)),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='TipoDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120, unique=True)),
                ('descricao', models.TextField(blank=True)),
                ('extensoes_permitidas', models.CharField(default='pdf', max_length=100)),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='TipoEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120, unique=True)),
                ('descricao', models.TextField(blank=True)),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Tipo de Evento',
                'verbose_name_plural': 'Tipos de Eventos',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='CPR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('sigla', models.CharField(max_length=20)),
                ('ativo', models.BooleanField(default=True)),
                ('coppm', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cprs', to='solicitacoes.coppm')),
            ],
            options={
                'ordering': ['sigla'],
            },
        ),
        migrations.CreateModel(
            name='CampoPersonalizado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
                ('label', models.CharField(max_length=150)),
                ('tipo', models.CharField(choices=[('texto', 'Texto'), ('numero', 'Número'), ('data', 'Data'), ('hora', 'Hora'), ('boolean', 'Sim / Não'), ('lista', 'Lista'), ('textarea', 'Texto Longo')], max_length=20)),
                ('obrigatorio', models.BooleanField(default=False)),
                ('ordem', models.PositiveIntegerField(default=0)),
                ('ajuda', models.CharField(blank=True, max_length=250)),
                ('ativo', models.BooleanField(default=True)),
                ('modulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campos', to='solicitacoes.modulo')),
            ],
            options={
                'ordering': ['ordem', 'label'],
            },
        ),
        migrations.CreateModel(
            name='Bairro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
                ('ativo', models.BooleanField(default=True)),
                ('municipio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bairros', to='solicitacoes.municipio')),
            ],
            options={
                'ordering': ['nome'],
                'unique_together': {('municipio', 'nome')},
            },
        ),
        migrations.CreateModel(
            name='OpcaoCampo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.CharField(max_length=120)),
                ('ordem', models.PositiveIntegerField(default=0)),
                ('campo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opcoes', to='solicitacoes.campopersonalizado')),
            ],
            options={
                'ordering': ['ordem', 'valor'],
            },
        ),
        migrations.CreateModel(
            name='Solicitacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('protocolo', models.CharField(blank=True, max_length=20, unique=True)),
                ('nome_evento', models.CharField(max_length=250)),
                ('solicitante', models.CharField(max_length=200)),
                ('cpf', models.CharField(max_length=14)),
                ('email', models.EmailField(max_length=254)),
                ('telefone', models.CharField(max_length=20)),
                ('local', models.TextField()),
                ('publico_estimado', models.PositiveIntegerField()),
                ('data_evento', models.DateField()),
                ('hora_inicio', models.TimeField()),
                ('hora_fim', models.TimeField()),
                ('observacoes', models.TextField(blank=True)),
                ('parecer_operacional', models.TextField(blank=True)),
                ('aprovado_por', models.CharField(blank=True, max_length=150)),
                ('data_aprovacao', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('RASCUNHO', 'Rascunho'), ('ENVIADA', 'Enviada'), ('EM_ANALISE', 'Em análise'), ('PENDENTE', 'Pendente'), ('CORRECAO', 'Correção'), ('APROVADA', 'Aprovada'), ('REJEITADA', 'Rejeitada'), ('CONCLUIDA', 'Concluída')], default='RASCUNHO', max_length=20)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('bairro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='solicitacoes.bairro')),
                ('municipio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='solicitacoes.municipio')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('tipo_evento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='solicitacoes.tipoevento')),
            ],
        ),
        migrations.CreateModel(
            name='LogSistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acao', models.CharField(max_length=200)),
                ('detalhes', models.TextField(blank=True)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('solicitacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='solicitacoes.solicitacao')),
            ],
            options={
                'verbose_name': 'Log',
                'verbose_name_plural': 'Logs',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='HistoricoSolicitacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=40)),
                ('observacao', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('solicitacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico', to='solicitacoes.solicitacao')),
            ],
            options={
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='AnexoOPO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(upload_to=apps.solicitacoes.models.pasta_opo)),
                ('descricao', models.CharField(blank=True, max_length=250)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('solicitacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opos', to='solicitacoes.solicitacao')),
            ],
        ),
        migrations.CreateModel(
            name='SolicitacaoModulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modulo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='solicitacoes.modulo')),
                ('solicitacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modulos', to='solicitacoes.solicitacao')),
            ],
            options={
                'unique_together': {('solicitacao', 'modulo')},
            },
        ),
        migrations.CreateModel(
            name='DocumentoSolicitacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(blank=True, max_length=250)),
                ('arquivo', models.FileField(upload_to=apps.solicitacoes.models.upload_documento, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])])),
                ('enviado_em', models.DateTimeField(auto_now_add=True)),
                ('solicitacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='solicitacoes.solicitacao')),
                ('tipo_documento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='solicitacoes.tipodocumento')),
            ],
            options={
                'ordering': ['tipo_documento', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Unidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('sigla', models.CharField(max_length=30)),
                ('tipo', models.CharField(choices=[('BPM', 'BPM'), ('CIPM', 'CIPM'), ('CIPE', 'CIPE'), ('CPR', 'CPR'), ('ESPECIALIZADA', 'Especializada'), ('OUTRA', 'Outra')], max_length=30)),
                ('telefone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('ativo', models.BooleanField(default=True)),
                ('cpr', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='unidades', to='solicitacoes.cpr')),
            ],
            options={
                'ordering': ['sigla'],
            },
        ),
        migrations.AddField(
            model_name='solicitacao',
            name='unidade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='solicitacoes', to='solicitacoes.unidade'),
        ),
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('perfil', models.CharField(choices=[('ADMIN', 'Administrador Geral'), ('COPPM', 'COPPM'), ('CPR', 'CPR'), ('UNIDADE', 'Unidade'), ('OPERADOR', 'Operador'), ('CONSULTA', 'Consulta')], max_length=30)),
                ('ativo', models.BooleanField(default=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_siev', to=settings.AUTH_USER_MODEL)),
                ('unidade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='solicitacoes.unidade')),
            ],
            options={
                'verbose_name': 'Perfil',
                'verbose_name_plural': 'Perfis',
            },
        ),
        migrations.AddField(
            model_name='municipio',
            name='unidade_responsavel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='municipios', to='solicitacoes.unidade'),
        ),
        migrations.CreateModel(
            name='MatriculaAutorizada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricula', models.CharField(max_length=20, unique=True)),
                ('nome', models.CharField(max_length=150)),
                ('posto', models.CharField(blank=True, max_length=30)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('unidade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='solicitacoes.unidade')),
            ],
            options={
                'verbose_name': 'Matrícula Autorizada',
                'verbose_name_plural': 'Matrículas Autorizadas',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='ConfiguracaoUnidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('obrigatorio', models.BooleanField(default=False)),
                ('ativo', models.BooleanField(default=True)),
                ('modulo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='solicitacoes.modulo')),
                ('tipo_documento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='solicitacoes.tipodocumento')),
                ('unidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='configuracoes', to='solicitacoes.unidade')),
            ],
            options={
                'verbose_name': 'Configuração da Unidade',
                'verbose_name_plural': 'Configurações das Unidades',
            },
        ),
        migrations.CreateModel(
            name='AreaResponsabilidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ativo', models.BooleanField(default=True)),
                ('bairro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='solicitacoes.bairro')),
                ('unidade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='solicitacoes.unidade')),
            ],
            options={
                'verbose_name': 'Área de Responsabilidade',
                'verbose_name_plural': 'Áreas de Responsabilidade',
                'unique_together': {('bairro', 'unidade')},
            },
        ),
        migrations.CreateModel(
            name='ValorCampo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.TextField()),
                ('campo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='solicitacoes.campopersonalizado')),
                ('solicitacao_modulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valores', to='solicitacoes.solicitacaomodulo')),
            ],
            options={
                'unique_together': {('solicitacao_modulo', 'campo')},
            },
        ),
    ]
