# Generated by Django 6.0.5 on 2026-08-10 21:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitacoes', '0002_alter_solicitacao_unidade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitacao',
            name='tipo_evento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='solicitacoes.tipoevento'),
        ),
    ]
