# Generated by Django 6.0.5 on 2026-08-10 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitacoes', '0003_alter_solicitacao_tipo_evento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitacao',
            name='publico_estimado',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
