# Generated by Django 6.0.5 on 2026-08-11 15:59

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitacoes', '0004_alter_solicitacao_publico_estimado'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='perfilusuario',
            options={'verbose_name': 'Perfil de Usuário', 'verbose_name_plural': 'Perfis de Usuários'},
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='atualizado_em',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='cpr',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gestores_siev', to='solicitacoes.cpr'),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='criado_em',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='perfil',
            field=models.CharField(choices=[('COPPM', 'Gestor COPPM'), ('CPR', 'Gestor CPR'), ('UNIDADE', 'Gestor de Unidade')], max_length=20),
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='unidade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gestores_siev', to='solicitacoes.unidade'),
        ),
    ]
