# Generated by Django 6.0.5 on 2026-08-14 15:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitacoes', '0006_solicitacao_origem_transferenciasolicitacao'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='historicosolicitacao',
            name='acao',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='historicosolicitacao',
            name='status_anterior',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='historicosolicitacao',
            name='status_novo',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='historicosolicitacao',
            name='unidade_anterior',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historicos_unidade_anterior', to='solicitacoes.unidade'),
        ),
        migrations.AddField(
            model_name='historicosolicitacao',
            name='unidade_nova',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historicos_unidade_nova', to='solicitacoes.unidade'),
        ),
        migrations.AlterField(
            model_name='historicosolicitacao',
            name='status',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='historicosolicitacao',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historicos_siev', to=settings.AUTH_USER_MODEL),
        ),
    ]
